from typing import Protocol
from uuid import UUID
from .entities import Order


class OrderRepository(Protocol):
    def create(self, order: Order) -> Order: ...
    def get(self, order_id: UUID) -> Order | None: ...
    def list(self) -> list[Order]: ...
    def list_claimable(self) -> list[Order]: ...  # pending & lewat cooldown, tertua dulu
    def save(self, order: Order) -> Order: ...


class BotInventoryRepository(Protocol):
    def upsert(self, bot_id: UUID, inventory: dict) -> None: ...
    def get(self, bot_id: UUID) -> dict: ...
