"""baseline schema

Revision ID: d427fff41aa3
Revises: 
Create Date: 2026-08-01 17:37:28.190840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd427fff41aa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_inventories',
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_table('bots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('game', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=32), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server', sa.String(length=120), nullable=True),
    sa.Column('ping_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bots_last_heartbeat_at'), ['last_heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_token_prefix'), ['token_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_username'), ['username'], unique=True)

    op.create_table('channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_type'), ['type'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient', sa.String(length=120), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_bot', sa.String(length=120), nullable=True),
    sa.Column('sent_total', sa.Integer(), nullable=False),
    sa.Column('requested_total', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('release_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_recipient'), ['recipient'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'dedupe_key', name='uq_webhook_source_dedupe')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_source'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_event'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_source'))
        batch_op.drop_index(batch_op.f('ix_orders_recipient'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_type'))

    op.drop_table('channels')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bots_username'))
        batch_op.drop_index(batch_op.f('ix_bots_token_prefix'))
        batch_op.drop_index(batch_op.f('ix_bots_status'))
        batch_op.drop_index(batch_op.f('ix_bots_last_heartbeat_at'))

    op.drop_table('bots')
    op.drop_table('bot_inventories')
    # ### end Alembic commands ###
